%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=postgres
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/lyn
%dev.quarkus.hibernate-orm.log.sql=true
mp.jwt.verify.issuer=mario-russo
smallrye.jwt.sign.key.location=file:${JWT_PRIVATE_KEY:./secrets/privateKey.pem}
mp.jwt.verify.publickey.location=file:${JWT_PUBLIC_KEY:./secrets/publicKey.pem}
smallrye.jwt.sign.algorithm=RS256
jwt.expiration=3600
jwt.refresh-expiration=86400
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql