-- This file allow to write SQL commands that will be emitted in test and dev.
-- The commands are commented as their support depends of the database
-- insert into myentity (id, field) values(1, 'field-1');
-- insert into myentity (id, field) values(2, 'field-2');
-- insert into myentity (id, field) values(3, 'field-3');
-- alter sequence myentity_seq restart with
CREATE TABLE IF NOT EXISTS empresa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cnpj VARCHAR(14) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    email VARCHAR(255),
    endereco_logradouro VARCHAR(255),
    endereco_municipio VARCHAR(255),
    endereco_estado VARCHAR(2),
    usuario_id BIGINT,
    active BOOLEAN DEFAULT TRUE,
    date_create TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    date_update TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS funcionario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    empresa_id BIGINT
);

CREATE TABLE IF NOT EXISTS empresa_funcionarios (
    empresa_id BIGINT NOT NULL,
    funcionario_id BIGINT NOT NULL,
    PRIMARY KEY (empresa_id, funcionario_id),
    CONSTRAINT fk_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id) ON DELETE CASCADE
);


-- Limpa dados anteriores caso o banco não seja dropado
TRUNCATE TABLE empresa_funcionarios CASCADE;
TRUNCATE TABLE funcionario_servicos CASCADE;
TRUNCATE TABLE funcionario CASCADE;
TRUNCATE TABLE empresa CASCADE;

-- ============================================================================
-- 2. DADOS DE TESTE (CNPJs Válidos para não quebrar seus Value Objects)
-- ============================================================================

-- Empresa 1
INSERT INTO empresa (id, name, cnpj, telefone, email, endereco_logradouro, endereco_municipio, endereco_estado, usuario_id, active, date_create, date_update)
VALUES (1, 'Russo Tecnologia LTDA', '47214732000109', '11999999999', 'contato@mariorusso.com.br', 'Avenida Paulista, 1000', 'São Paulo', 'SP', 101, TRUE, NOW(), NOW());

-- Empresa 2
INSERT INTO empresa (id, name, cnpj, telefone, email, endereco_logradouro, endereco_municipio, endereco_estado, usuario_id, active, date_create, date_update)
VALUES (2, 'Alpha Solucoes Digitais', '93386221000101', '21988888888', 'suporte@alpha.com', 'Rua Ouvidor, 50', 'Rio de Janeiro', 'RJ', 102, TRUE, NOW(), NOW());

-- Empresa 3
INSERT INTO empresa (id, name, cnpj, telefone, email, endereco_logradouro, endereco_municipio, endereco_estado, usuario_id, active, date_create, date_update)
VALUES (3, 'Omega Logistica', '08447834000114', '31977777777', 'vendas@omega.com.br', 'Av. Amazonas, 300', 'Belo Horizonte', 'MG', 103, FALSE, NOW(), NOW());


-- Funcionários
INSERT INTO funcionario (id, name, telefone, active, empresa_id) VALUES (1, 'Carlos Silva', '11911112222', TRUE, 1);
INSERT INTO funcionario (id, name, telefone, active, empresa_id) VALUES (2, 'Ana Costa', '11933334444', TRUE, 1);
INSERT INTO funcionario (id, name, telefone, active, empresa_id) VALUES (3, 'Bruno Souza', '21955556666', TRUE, 2);

-- Vinculação Empresa ↔ Funcionários
INSERT INTO empresa_funcionarios (empresa_id, funcionario_id) VALUES (1, 1);
INSERT INTO empresa_funcionarios (empresa_id, funcionario_id) VALUES (1, 2);
INSERT INTO empresa_funcionarios (empresa_id, funcionario_id) VALUES (2, 3);
--
-- -- Serviços dos Funcionários
-- INSERT INTO funcionario_servicos (funcionario_id, service_id) VALUES (1, 5);
-- INSERT INTO funcionario_servicos (funcionario_id, service_id) VALUES (1, 10);
-- INSERT INTO funcionario_servicos (funcionario_id, service_id) VALUES (2, 5);
-- INSERT INTO funcionario_servicos (funcionario_id, service_id) VALUES (3, 20);

-- ============================================================================
-- 3. AJUSTE DE SEQUENCES DO POSTGRESQL (Crucial para o fluxo de POST da aplicação)
-- ============================================================================
SELECT setval(pg_get_serial_sequence('empresa', 'id'), coalesce(max(id), 1)) FROM empresa;
SELECT setval(pg_get_serial_sequence('funcionario', 'id'), coalesce(max(id), 1)) FROM funcionario;



CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    data_create TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    active BOOLEAN DEFAULT TRUE,
    tipo VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario_roles (
    usuario_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (usuario_id, role),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- Limpa dados anteriores de usuários para evitar conflitos no reinício
TRUNCATE TABLE usuario_roles CASCADE;
TRUNCATE TABLE usuarios CASCADE;

-- Inserção do Usuário 1 (russo@gmail.com)
INSERT INTO usuarios (id, email, password, name, data_create, active, tipo)
VALUES (1, 'russo@gmail.com', 'mario', 'Mario Russo', NOW(), TRUE, 'EMPRESA');

-- Inserção do Usuário 2 (mario@gmail.com)
INSERT INTO usuarios (id, email, password, name, data_create, active, tipo)
VALUES (2, 'mario@gmail.com', 'mario', 'Mario Silva', NOW(), TRUE, 'EMPRESA');


-- Vinculação das Roles (Papéis de Acesso) na tabela auxiliar usuario_roles
INSERT INTO usuario_roles (usuario_id, role) VALUES (1, 'ESCRITA');
INSERT INTO usuario_roles (usuario_id, role) VALUES (2, 'ESCRITA');


-- Ajuste das Sequences de ID para a tabela de usuários (Evita o erro de Unique Constraint no POST)
--SELECT setval(pg_get_serial_sequence('usuarios', 'id'), coalesce(max(id), 1)) FROM usuarios;
--SELECT setval('usuarios_SEQ', coalesce(max(id), 1)) FROM usuarios;
SELECT setval(pg_get_serial_sequence('usuarios', 'id'), coalesce(max(id), 1)) FROM usuarios;