/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//(index)'
      | '//agendamento/'
      | '//agendamento/Dia'
      | '//agendamento/Semana'
      | '//dashboard/'
      | '//funcionario/'
      | '//second'
      | '//servicos/'
      | '//venda/'
    >,
    '//(index)': RouteRecordInfo<
      '//(index)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//agendamento/': RouteRecordInfo<
      '//agendamento/',
      '/agendamento',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//agendamento/Dia': RouteRecordInfo<
      '//agendamento/Dia',
      '/agendamento/Dia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//agendamento/Semana': RouteRecordInfo<
      '//agendamento/Semana',
      '/agendamento/Semana',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//dashboard/': RouteRecordInfo<
      '//dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//funcionario/': RouteRecordInfo<
      '//funcionario/',
      '/funcionario',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//second': RouteRecordInfo<
      '//second',
      '/second',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//servicos/': RouteRecordInfo<
      '//servicos/',
      '/servicos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//venda/': RouteRecordInfo<
      '//venda/',
      '/venda',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//(index)'
        | '//agendamento/'
        | '//agendamento/Dia'
        | '//agendamento/Semana'
        | '//dashboard/'
        | '//funcionario/'
        | '//second'
        | '//servicos/'
        | '//venda/'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(index).vue': {
      routes:
        | '//(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/agendamento/index.vue': {
      routes:
        | '//agendamento/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/agendamento/Dia.vue': {
      routes:
        | '//agendamento/Dia'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/agendamento/Semana.vue': {
      routes:
        | '//agendamento/Semana'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/dashboard/index.vue': {
      routes:
        | '//dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/funcionario/index.vue': {
      routes:
        | '//funcionario/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/second.vue': {
      routes:
        | '//second'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/servicos/index.vue': {
      routes:
        | '//servicos/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/venda/index.vue': {
      routes:
        | '//venda/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
